FROM python:3.10

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

WORKDIR /app

COPY . /app

RUN pip install --upgrade pip \
    && pip install -r requirements.txt
    
EXPOSE 8000
EXPOSE 5432

CMD ["python3", "manage.py", "runserver", "127.0.0.1:8000"]
