version: '3.8'

services:
  django:
    build: .
    container_name: backend_app
    command: sh -c "python manage.py makemigrations && \
                    python manage.py migrate && \
                    gunicorn back.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: always
    volumes:
      - .:/app
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - DJANGO_SETTINGS_MODULE=back.settings

  db:
    image: postgres:alpine
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=qwerty

  nginx:
    build:
      context: ./nginx/
    container_name: nginx
    depends_on:
      - django
    ports:
      - 80:80
    volumes:
      - .:/app

volumes:
  postgres_data:

