# Generated by Django 4.2.4 on 2023-12-05 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0013_remove_computervisionmodule_model_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerVisionModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv_modules_name', models.CharField(max_length=255)),
                ('cv_modules_description', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255)),
                ('model_description', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('FPS', 'FPS'), ('logging', 'Logging'), ('line_count', 'Line Count'), ('zone_check', 'Zone Check'), ('rtp_stream', 'RTP Stream'), ('box_drawing', 'Box Drawing'), ('buffer_stream', 'Stream Buffer'), ('FPS_check', 'FPS Check')], max_length=20)),
                ('fps', models.IntegerField(blank=True, null=True)),
                ('line_count', models.JSONField(blank=True, null=True)),
                ('zone_check', models.JSONField(blank=True, null=True)),
                ('host_rtp', models.CharField(blank=True, max_length=100, null=True)),
                ('port_rtp', models.IntegerField(blank=True, null=True)),
                ('size_buff', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')])),
                ('actions', models.ManyToManyField(to='processing.processaction')),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_url', models.URLField(default=None, null=True)),
                ('camera_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.camera')),
                ('cv_module_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processing.computervisionmodule')),
                ('process_events', models.ManyToManyField(to='processing.processevent')),
            ],
        ),
        migrations.AddField(
            model_name='computervisionmodule',
            name='model_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='processing.model'),
        ),
    ]
