# Generated by Django 4.2.4 on 2023-12-07 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0002_remove_process_process_events_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processevent',
            name='FPS_check',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processevent',
            name='box_drawing',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processevent',
            name='logging',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
