# Generated by Django 4.2.4 on 2023-12-07 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0003_processevent_fps_check_processevent_box_drawing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processevent',
            name='event_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
