# Generated by Django 4.2.4 on 2023-12-09 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0004_processevent_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('type1', 'Type 1'), ('type2', 'Type 2'), ('type3', 'Type 3'), ('type4', 'Type 4'), ('type5', 'Type 5'), ('type6', 'Type 6'), ('type7', 'Type 7'), ('type8', 'Type 8'), ('type9', 'Type 9')])),
                ('parameters', models.JSONField()),
            ],
        ),
        migrations.RemoveField(
            model_name='process',
            name='all_frames_event',
        ),
        migrations.RemoveField(
            model_name='process',
            name='any_object_event',
        ),
        migrations.RemoveField(
            model_name='process',
            name='any_object_few_minutes_event',
        ),
        migrations.RemoveField(
            model_name='processevent',
            name='FPS_check',
        ),
        migrations.RemoveField(
            model_name='processevent',
            name='box_drawing',
        ),
        migrations.RemoveField(
            model_name='processevent',
            name='fps',
        ),
        migrations.RemoveField(
            model_name='processevent',
            name='host_rtp',
        ),
        migrations.RemoveField(
            model_name='processevent',
            name='line_count',
        ),
        migrations.RemoveField(
            model_name='processevent',
            name='logging',
        ),
        migrations.RemoveField(
            model_name='processevent',
            name='port_rtp',
        ),
        migrations.RemoveField(
            model_name='processevent',
            name='size_buff',
        ),
        migrations.RemoveField(
            model_name='processevent',
            name='zone_check',
        ),
        migrations.AddField(
            model_name='process',
            name='events',
            field=models.ManyToManyField(to='processing.processevent'),
        ),
        migrations.AlterField(
            model_name='processevent',
            name='event_type',
            field=models.CharField(choices=[('type1', 'Type 1'), ('type2', 'Type 2'), ('type3', 'Type 3')], default='Не выбрано', max_length=10),
        ),
        migrations.AddField(
            model_name='processevent',
            name='actions',
            field=models.ManyToManyField(to='processing.processaction'),
        ),
    ]
