# Generated by Django 4.2.4 on 2023-12-09 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0005_processaction_remove_process_all_frames_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processaction',
            name='parameters',
            field=models.JSONField(null=True),
        ),
    ]
