# Generated by Django 4.2.4 on 2023-12-09 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0006_alter_processaction_parameters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processaction',
            name='parameters',
            field=models.JSONField(default=None, null=True),
        ),
    ]
