# Generated by Django 4.2.4 on 2024-01-18 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0013_actiontype_eventtype_alter_processaction_action_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actiontype',
            name='description',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='description',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
