# Generated by Django 4.2.4 on 2024-03-21 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camera_manager', '0002_alter_camera_input_location'),
        ('processing', '0015_rename_camera_id_process_camera_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='camera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_options', to='camera_manager.camera'),
        ),
    ]
