# Generated by Django 4.2.4 on 2023-12-14 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_name', models.CharField(max_length=255)),
                ('camera_ip', models.CharField(max_length=15)),
                ('camera_description', models.CharField(default='null', max_length=255, null=True)),
                ('camera_lat', models.FloatField(default=0.0)),
                ('camera_lon', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CameraGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GroupType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CameraToGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camera_manager.camera')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camera_manager.cameragroup')),
            ],
        ),
        migrations.AddField(
            model_name='cameragroup',
            name='group_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camera_manager.grouptype'),
        ),
        migrations.AddField(
            model_name='camera',
            name='input_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imput_location', to='camera_manager.location'),
        ),
        migrations.AddField(
            model_name='camera',
            name='output_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='output_location', to='camera_manager.location'),
        ),
    ]
