# Generated by Django 4.2.4 on 2024-02-12 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camera_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='input_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_location', to='camera_manager.location'),
        ),
    ]
