# Generated by Django 4.2.4 on 2024-03-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera_manager', '0002_alter_camera_input_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='coordinates',
            field=models.JSONField(default=list),
        ),
    ]
