# Generated by Django 4.2.4 on 2023-08-26 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_name', models.CharField(max_length=255)),
                ('camera_ip', models.CharField(max_length=15)),
                ('camera_description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ClusterUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=255)),
                ('unit_ip', models.CharField(max_length=15)),
                ('unit_config', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='DetectedObjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Processing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processing_config', models.JSONField()),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.camera')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.clusterunit')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectsDetectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datestamp', models.DateTimeField()),
                ('count', models.IntegerField(default=0)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.location')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.detectedobjecttype')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datestamp', models.DateTimeField()),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.eventtype')),
                ('processing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.processing')),
            ],
        ),
        migrations.AddField(
            model_name='camera',
            name='input_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imput_location', to='api.location'),
        ),
        migrations.AddField(
            model_name='camera',
            name='output_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='output_location', to='api.location'),
        ),
    ]
