# Generated by Django 4.2.4 on 2023-11-20 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_event_video_url_processing_result_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_name', models.CharField(max_length=255)),
                ('action_description', models.CharField(max_length=255, null=True)),
                ('parameters', models.JSONField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255)),
                ('model_description', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_type',
            new_name='event_name',
        ),
        migrations.RenameField(
            model_name='eventtype',
            old_name='event_type',
            new_name='event_name',
        ),
        migrations.AddField(
            model_name='eventtype',
            name='event_description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='parameters',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.CreateModel(
            name='ComputerVisionModules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv_modules_name', models.CharField(max_length=255)),
                ('cv_modules_description', models.CharField(max_length=255, null=True)),
                ('model_type', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.models')),
            ],
        ),
    ]
