# Generated by Django 4.2.4 on 2023-11-20 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_action_models_rename_event_type_event_event_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectedobjecttype',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
