# Generated by Django 4.2.4 on 2023-11-20 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_computervisionmodules_computervisionmodule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.camera')),
                ('cv_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.computervisionmodule')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameters', models.JSONField(default=None, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.eventtype')),
            ],
        ),
        migrations.AddField(
            model_name='processing',
            name='channel',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='processing',
            name='cv_module',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='api.computervisionmodule'),
        ),
        migrations.AddField(
            model_name='processing',
            name='ip',
            field=models.CharField(default='0.0.0.0', max_length=15),
        ),
        migrations.AddField(
            model_name='processing',
            name='login',
            field=models.CharField(default='admin', max_length=255),
        ),
        migrations.AddField(
            model_name='processing',
            name='password',
            field=models.CharField(default='bvrn2022', max_length=255),
        ),
        migrations.AddField(
            model_name='processing',
            name='port',
            field=models.CharField(default='5432', max_length=4),
        ),
        migrations.AddField(
            model_name='processing',
            name='scene_number',
            field=models.CharField(default='1', max_length=255),
        ),
        migrations.CreateModel(
            name='ProcessToProcessEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.process')),
                ('process_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.processevent')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessEventToAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.action')),
                ('process_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.processevent')),
            ],
        ),
    ]
