# Generated by Django 4.2.4 on 2023-11-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_process_processevent_processing_channel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processtoprocessevent',
            name='process',
        ),
        migrations.RemoveField(
            model_name='processtoprocessevent',
            name='process_event',
        ),
        migrations.AddField(
            model_name='process',
            name='process_events',
            field=models.ManyToManyField(to='api.processevent'),
        ),
        migrations.AddField(
            model_name='processevent',
            name='actions',
            field=models.ManyToManyField(to='api.action'),
        ),
        migrations.DeleteModel(
            name='ProcessEventToAction',
        ),
        migrations.DeleteModel(
            name='ProcessToProcessEvent',
        ),
    ]
