# Generated by Django 4.2.4 on 2023-11-21 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_processtoprocessevent_process_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GroupType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='processing',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='processing',
            name='cv_module',
        ),
        migrations.RemoveField(
            model_name='processing',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='processing',
            name='login',
        ),
        migrations.RemoveField(
            model_name='processing',
            name='password',
        ),
        migrations.RemoveField(
            model_name='processing',
            name='port',
        ),
        migrations.RemoveField(
            model_name='processing',
            name='scene_number',
        ),
        migrations.AlterField(
            model_name='camera',
            name='camera_description',
            field=models.CharField(default='null', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='processing',
            name='processing_config',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.CreateModel(
            name='CameraToGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.camera')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cameragroup')),
            ],
        ),
        migrations.AddField(
            model_name='cameragroup',
            name='group_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.grouptype'),
        ),
    ]
