# Generated by Django 4.2.4 on 2023-11-23 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_cameragroup_grouptype_remove_processing_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='camera_lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='camera',
            name='camera_lon',
            field=models.FloatField(default=0.0),
        ),
    ]
