# Generated by Django 4.2.4 on 2023-12-05 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_process_result_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processing',
            name='camera',
        ),
        migrations.RemoveField(
            model_name='processing',
            name='unit',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Processing',
        ),
    ]
