# Generated by Django 4.2.4 on 2023-12-05 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_processing_camera_remove_processing_unit_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClusterUnit',
        ),
    ]
