# Generated by Django 4.2.4 on 2023-12-05 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_delete_clusterunit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computervisionmodule',
            name='model_type',
        ),
        migrations.RemoveField(
            model_name='process',
            name='camera',
        ),
        migrations.RemoveField(
            model_name='process',
            name='cv_module',
        ),
        migrations.RemoveField(
            model_name='process',
            name='process_events',
        ),
        migrations.RemoveField(
            model_name='processevent',
            name='actions',
        ),
        migrations.RemoveField(
            model_name='processevent',
            name='event',
        ),
        migrations.DeleteModel(
            name='Action',
        ),
        migrations.DeleteModel(
            name='ComputerVisionModule',
        ),
        migrations.DeleteModel(
            name='EventType',
        ),
        migrations.DeleteModel(
            name='Model',
        ),
        migrations.DeleteModel(
            name='Process',
        ),
        migrations.DeleteModel(
            name='ProcessEvent',
        ),
    ]
