# Generated by Django 4.2.4 on 2023-12-14 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camera_manager', '0001_initial'),
        ('processing', '0012_alter_process_camera_id'),
        ('api', '0013_remove_computervisionmodule_model_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cameragroup',
            name='group_type',
        ),
        migrations.RemoveField(
            model_name='cameratogroup',
            name='camera_id',
        ),
        migrations.RemoveField(
            model_name='cameratogroup',
            name='group_id',
        ),
        migrations.AlterField(
            model_name='objectsdetectionlog',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camera_manager.location'),
        ),
        migrations.DeleteModel(
            name='Camera',
        ),
        migrations.DeleteModel(
            name='CameraGroup',
        ),
        migrations.DeleteModel(
            name='CameraToGroup',
        ),
        migrations.DeleteModel(
            name='GroupType',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
