# Generated by Django 4.2.4 on 2024-01-18 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camera_manager', '0001_initial'),
        ('api', '0014_remove_cameragroup_group_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('change', models.IntegerField()),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camera_manager.camera')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camera_manager.location')),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event', models.TextField()),
                ('incident', models.TextField()),
                ('link', models.URLField()),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camera_manager.camera')),
            ],
        ),
    ]
