# Generated by Django 4.2.4 on 2024-02-13 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_zonestats_incident'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='event',
        ),
    ]
