# Generated by Django 4.2.4 on 2024-02-13 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_incident_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incident',
            old_name='incident',
            new_name='incident_type',
        ),
    ]
