# Generated by Django 4.2.4 on 2024-02-13 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_incidenttype_alter_incident_incident_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='incident_type',
            field=models.CharField(max_length=255),
        ),
    ]
