# Generated by Django 4.2.4 on 2024-02-13 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_incident_incident_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='incident_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.incidenttype'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='link',
            field=models.URLField(default=None, null=True),
        ),
    ]
