# Generated by Django 4.2.4 on 2024-02-18 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_incident_incident_type_alter_incident_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='link',
            field=models.URLField(blank=True, default=None),
        ),
    ]
