# Generated by Django 4.2.4 on 2024-02-18 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_incident_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zonestats',
            name='location',
        ),
    ]
