# Generated by Django 4.2.4 on 2024-02-18 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camera_manager', '0002_alter_camera_input_location'),
        ('api', '0023_remove_zonestats_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zonestats',
            name='camera',
        ),
        migrations.AddField(
            model_name='zonestats',
            name='location',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='camera_manager.location'),
        ),
        migrations.AddField(
            model_name='zonestats',
            name='value',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='zonestats',
            name='change',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CameraStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('input_value', models.IntegerField()),
                ('output_value', models.IntegerField()),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camera_manager.camera')),
            ],
        ),
    ]
