# Generated by Django 4.2.4 on 2024-03-14 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camera_manager', '0002_alter_camera_input_location'),
        ('api', '0025_rename_camerastats_camerastat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camerastat',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='zonestat',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camera_manager.location'),
        ),
        migrations.AlterField(
            model_name='zonestat',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
