# Generated by Django 4.2.4 on 2024-06-09 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0026_alter_camerastat_timestamp_alter_zonestat_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incident',
            old_name='timestamp',
            new_name='start_timestamp',
        ),
        migrations.AddField(
            model_name='incident',
            name='end_timestamp',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='operator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В обработке'), ('closed', 'Закрыто')], default='new', max_length=20),
        ),
    ]
