# Generated by Django 4.2.4 on 2024-06-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_rename_timestamp_incident_start_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='end_timestamp',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
